[package]
name = "scratch"
version = "0.12.19-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
printer = { path = "../printer" }
