---

name: Clippy a release
on:
  repository_dispatch:
    types: [new-release]

jobs:
  pre-check:
    if: ${{ github.event.client_payload.is_new_release }}
    runs-on: ubuntu-20.04
    steps:
      - name: Exit if not on master branch
        if: endsWith(github.ref, 'main') == false
        run: exit 1

      - uses: actions/checkout@v3
        with:
          ref: ${{  github.event.client_payload.sha }}

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.client_payload.version }}
          regex: '^v[0-9]+\.[0-9]+\.[0-9]+$'

      - name: Deploy version if version string is valid
        if: ${{ steps.regex-match.outputs.match != '' }} # only deploy versions in the form of `v0.12.3` do not supported suffixes.
        run: |
          cargo --version
          cargo clippy

  call-workflow:
    needs: pre-check
    uses: ./.github/workflows/clippy.yml
    with:
      sha: ${{ github.sha }}
