---

name: Clippy a release
on:
  repository_dispatch:
    types: [new-release]

jobs:
  style:
    runs-on: ubuntu-20.04
    steps:
      - name: Exit if not on master branch
        if: endsWith(github.ref, 'main') == false
        run: exit 1

      - uses: actions/checkout@v3

      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true

      - name: Clippy
        run: |
          cargo --version
          cargo clippy
