---
name: "Reusable grcov workflow"

on:
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
    outputs:
      path:
        description: "Location of grcov html files"
        value: ${{ jobs.grcov.outputs.path }}

jobs:
  grcov:
    runs-on: ubuntu-20.04
    outputs:
      path: ${{ steps.coverage.outputs.report }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{  inputs.sha }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - uses: actions-rs/cargo@v1
        with:
          command: clean

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast  # Customize args for your own needs
        env:
          CARGO_INCREMENTAL: '0'
          RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
          RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
      - id: coverage
        uses: actions-rs/grcov@v0.1

