name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  grcov:
    runs-on: ubuntu-22.04
    uses: ./.github/workflows/coverage.yml
    with:
      sha: ${{ github.sha }}

  build:
    needs: grcov
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
