name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  grcov:
    uses: ./.github/workflows/coverage.yml
    with:
      sha: ${{ github.sha }}

  build:
    needs: grcov
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
