name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
    contents: write

jobs:
  grcov:
    uses: ./.github/workflows/coverage.yml
    with:
      sha: ${{ github.sha }}
      artifact-name: coverage

  build:
    needs: grcov
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: coverage
          path: docs
      - name: ls docs folder
        shell: bash
        run: |
          ls docs/
          echo "break"
#          ls docs/coverage
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
