---
name: Python

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pyscript:
    runs-on: ubuntu-22.04
    outputs:
      version: ${{ steps.version-output.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install requirements-parser
      - uses: jannekem/run-python-script-action@v1
        id: version-output
        with:
          script: |
            import requirements
            import os
            with open('pycode/requirements.txt', 'r') as fd:
                 for req in requirements.parse(fd):
                     if req.name == "sample":
                         os.environ['GITHUB_OUTPUT'] = f"version={req.specs[0][1]}"
                         print(f"version={req.specs[0][1]}")
  prove-it:
    needs: pyscript
    runs-on: ubuntu-22.04
    steps:
      - name: proof
        shell: bash
        run: |
          echo "The version is: ${{ needs.pyscript.outputs.version }}"
