---
name: "Tag on Pull Request merge"

on:
  # Should trigger only when a Pull Request is Closed
  # (the action will not create the Tag if the Pull Request is discarded - closed without merge)
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  version-check:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - run: git fetch --all --tags

      - name: Extract version from Cargo.toml
        uses: thebongy/version-check@v1
        id: check_version
        with:
          file: scratch/Cargo.toml
          failBuild: false # don't want CI to fail if the tag does exist, later logic ensures tag must be new.
          tagFormat: v${version}

      - name: Create tag on main but only if it does not exist
        uses: rickstaa/action-create-tag@v1
        id: tag_create
        with:
          tag_exists_error: false # don't want CI to fail if the tag does exist, later logic ensures tag must be new.
          tag: "${{ steps.check_version.outputs.releaseVersion }}"

      # Print result using the action output.
      - run: |
          echo "Tag ${{ steps.check_version.outputs.releaseVersion }} already present: ${{ steps.tag_create.outputs.tag_exists }}"

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: new-release
          client-payload: "{ \"is_new_release\": ${{ steps.tag_create.outputs.tag_exists == 'false' }}, \"sha\": \"${{ github.sha }}\", \"version\": \"${{ steps.check_version.outputs.releaseVersion }}\" }"

