---
name: "Tag on Pull Request merge"

on:
  # Should trigger only when a Pull Request is Closed
  # (the action will not create the Tag if the Pull Request is discarded - closed without merge)
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  version-check:
    permissions: write-all
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - run: git fetch --all --tags

      - name: Extract version from binary's Cargo.toml
        uses: thebongy/version-check@v1
        id: check_bin_version
        with:
          file: scratch/Cargo.toml
          failBuild: false # don't want CI to fail if the tag does exist, later logic ensures tag must be new.
          tagFormat: v${version}

      - name: Extract version from library's Cargo.toml
        uses: thebongy/version-check@v1
        id: check_lib_version
        with:
          file: printer/Cargo.toml
          failBuild: false # don't want CI to fail if the tag does exist, later logic ensures tag must be new.
          tagFormat: v${version}

      - name: Tags do not match only deploy release versions if binary matches library versions
        if: ${{ steps.check_bin_version.outputs.releaseVersion != steps.check_lib_version.outputs.releaseVersion }}
        run: |
          echo "Tag bin version ${{ steps.check_bin_version.outputs.releaseVersion }} does NOT match tag lib version, will not trigger subsequent workflow"

      - name: Create tag on main but only if it does not exist
        if: ${{ steps.check_bin_version.outputs.releaseVersion == steps.check_lib_version.outputs.releaseVersion }}
        uses: rickstaa/action-create-tag@v1
        id: tag_create
        with:
          tag_exists_error: false # don't want CI to fail if the tag does exist, later logic ensures tag must be new.
          tag: "${{ steps.check_bin_version.outputs.releaseVersion }}"

      - name: Announce tag version and whether or not the tag already exists in the repo
        run: |
          echo "Tag bin version ${{ steps.check_bin_version.outputs.releaseVersion }}.  Tag already present: ${{ steps.tag_create.outputs.tag_exists }}"
        if: ${{ steps.check_bin_version.outputs.releaseVersion == steps.check_lib_version.outputs.releaseVersion }}

      - name: Repository Dispatch
        if: ${{ steps.check_bin_version.outputs.releaseVersion == steps.check_lib_version.outputs.releaseVersion }}
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: new-release
          client-payload: "{ \"is_new_release\": ${{ steps.tag_create.outputs.tag_exists == 'false' }}, \"sha\": \"${{ github.sha }}\", \"version\": \"${{ steps.check_bin_version.outputs.releaseVersion }}\" }"

