---
name: Cargo Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - name: Build all tests
        run: cargo test --workspace --all-features --no-run
        timeout-minutes: 20

      - name: Run all tests
        run: cargo test --no-fail-fast --workspace --all-features
        timeout-minutes: 20
